# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170521_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 0, 44, 57, 383000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 0, 44, 57, 383000, tzinfo=utc)),
        ),
    ]
