# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170521_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 0, 45, 1, 728000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 22, 0, 45, 1, 727000, tzinfo=utc)),
        ),
    ]
