# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:18
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170521_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
