# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170522_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
