# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170522_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
