# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=redactor.fields.RedactorField(),
        ),
    ]
